[package]
name = "sqlgen"
version = "0.1.0"
edition = "2021"
authors = ["Franklin E. Blanco"]
description = ""
license = "MIT"
readme = "README.md"
repository = ""
documentation = ""

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
sqlparser = "0.35.0"